spring:
  application:
    name: arcloa

loa:
  base:
    url: https://developer-lostark.game.onstove.com/
  token:
    bearer: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IktYMk40TkRDSTJ5NTA5NWpjTWk5TllqY2lyZyIsImtpZCI6IktYMk40TkRDSTJ5NTA5NWpjTWk5TllqY2lyZyJ9.eyJpc3MiOiJodHRwczovL2x1ZHkuZ2FtZS5vbnN0b3ZlLmNvbSIsImF1ZCI6Imh0dHBzOi8vbHVkeS5nYW1lLm9uc3RvdmUuY29tL3Jlc291cmNlcyIsImNsaWVudF9pZCI6IjEwMDAwMDAwMDA1NTk5MTQifQ.CBICDiojAqtUZZ4lnqhXHhp0QwN8HINj_nUYIPO6JVTao8BzlhOU15ZKw3fEMgrSaSyG78y_V-T-md6Jw0liZj-NKjtlkAiehZ3WItwob5i3leraqqF2LKCsDJ1Lpa37bSAyOEp18q504JAJFlr14o7Ff-VM6iUZbKhzaX4jH8jaJBm6XctIrDvWEEbCxTJuoTQt7vWC5WRyyDR5YU8ocGvMggr09fWYKDE4ShBZ_l2nnkwTLWNU4lN6wlXu62mtrqsUn3qdhO5LpVbGp8hs9P5YUHP8Bjrav_iDkxz3-ThBz_HKNM5Ls4NapiZtYfEH2nl4956Ctqvo9ca0TCu_mA
